[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[redirects]]
  from = "/github"
  to = "https://github.com/Pigletpeakkung"
  status = 301

[[redirects]]
  from = "/voice123"
  to = "https://voice123.com/thanatsitt"
  status = 301

[[redirects]]
  from = "/linktree"
  to = "https://linktr.ee/ThanttEzekiel"
  status = 301

[[redirects]]
  from = "/youtube"
  to = "https://youtube.com/@pegearts"
  status = 301
