# Astrotrias Archon - Netlify Configuration
# Author: Thanatsitt Santisamranwilai (Astrotrias Archon)
# Version: 2.1.2 - Simplified for Deployment

[build]
  publish = "."
  command = ""
  
[build.environment]
  NODE_VERSION = "20"

# Performance & Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    X-DNS-Prefetch-Control = "on"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache Control for Static Assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# PWA Files
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Main Index - Always Fresh
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Legacy Repository Redirects
[[redirects]]
  from = "https://pigletpeakkung.github.io/Codex-Terra-Arcanum/*"
  to = "https://astrotrias-archon.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://pigletpeakkung.github.io/Astrotrias-Archon/*"
  to = "https://astrotrias-archon.netlify.app/:splat"
  status = 301
  force = true

# Cosmic Navigation Redirects
[[redirects]]
  from = "/home"
  to = "/#home"
  status = 301

[[redirects]]
  from = "/projects"
  to = "/#dimensions"
  status = 301

[[redirects]]
  from = "/about"
  to = "/#timeline"
  status = 301

[[redirects]]
  from = "/skills"
  to = "/#skills"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/#contact"
  status = 301

# Social Media Shortcuts
[[redirects]]
  from = "/github"
  to = "https://github.com/Pigletpeakkung"
  status = 302

[[redirects]]
  from = "/voice123"
  to = "https://voice123.com/thanatsitt"
  status = 302

[[redirects]]
  from = "/linktree"
  to = "https://linktr.ee/ThanttEzekiel"
  status = 302

# SPA Fallback (Must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Edge Functions Configuration
[[edge_functions]]
  path = "/*"
  function = "headers"

# Development Settings
[dev]
  command = "npx live-server . --port=3000"
  port = 3000
  publish = "."
