# ===============================================
# ASTROTRIAS PORTFOLIO - EDGE FUNCTIONS CONFIG
# Optimized for performance, learning, and personalization
# ===============================================

[build]
  edge_functions = "netlify/edge-functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  EDGE_FUNCTIONS_VERSION = "1.0"
  ANALYTICS_ENABLED = "true"

# ===============================================
# CORE FUNCTIONALITY
# ===============================================

# 1. Security Headers (Always first)
[[edge_functions]]
function = "security-headers"
path = "/*"
priority = 1

# 2. Bot Filtering (Allow search engines)
[[edge_functions]]
function = "bot-filter"
path = "/*"
priority = 2
excludedPath = ["/robots.txt", "/sitemap.xml"]

# 3. Image Optimization
[[edge_functions]]
function = "image-optimizer"
path = "/images/*"
cache = "edge"

[edge_functions.image-optimizer]
  quality = 80
  formats = ["webp", "avif"]

# ===============================================
# PERSONALIZATION
# ===============================================

# 1. Theme Detection (Dark/Light mode)
[[edge_functions]]
function = "theme-detector"
path = "/*"
priority = 5

# 2. Geolocation Welcome Message
[[edge_functions]]
function = "geo-welcome"
path = "/"
cache = "manual"

# ===============================================
# PERFORMANCE OPTIMIZATIONS
# ===============================================

# 1. Critical CSS Injection
[[edge_functions]]
function = "critical-css"
path = "/*"
cache = "edge"

# 2. Smart Preloading
[[edge_functions]]
function = "resource-preloader"
path = "/*"
cache = "edge"

# ===============================================
# LEARNING EXPERIMENTS
# ===============================================

# 1. A/B Testing Layouts
[[edge_functions]]
function = "ab-testing"
path = "/"
cache = "manual"

[edge_functions.ab-testing]
  variants = ["layout-a", "layout-b"]
  weights = [50, 50]

# 2. Visitor Counter (Edge KV Storage)
[[edge_functions]]
function = "visitor-counter"
path = "/"
cache = "manual"

# ===============================================
# API ENDPOINTS
# ===============================================

# 1. Contact Form
[[edge_functions]]
function = "contact-handler"
path = "/api/contact"
cache = "manual"

# 2. Project Data
[[edge_functions]]
function = "projects-api"
path = "/api/projects"
cache = "edge"

# ===============================================
# ENVIRONMENT-SPECIFIC SETTINGS
# ===============================================

[contexts.dev]
  [[contexts.dev.edge_functions]]
  function = "debug-headers"
  path = "/*"

[contexts.production]
  [[contexts.production.edge_functions]]
  function = "rate-limiter"
  path = "/api/*"
  priority = 3

# ===============================================
# ERROR HANDLING
# ===============================================

[edge_functions.error-pages]
  404 = "/404.html"
  500 = "/error.html"

# ===============================================
# FEATURE FLAGS
# ===============================================

[feature_flags]
  dark_mode = true
  visitor_counter = true
  ab_testing = false  # Disabled by default

# ===============================================
# MONITORING
# ===============================================

# Privacy-focused analytics
[[edge_functions]]
function = "plausible-proxy"
path = "/api/analytics"
cache = "manual"

# ===============================================
# DEPLOYMENT SETTINGS
# ===============================================

[deploy]
  auto_rollback = true
  health_check_path = "/health"
